#!/bin/bash

read NICKNAME

parameter=$(node -e "console.log(encodeURIComponent('$NICKNAME'))")
participant=$1
echo $parameter

if [ "$cookies" = "" ]; then
	cookies=$(cat integration/cookies)
fi

if [ "$csrf" = "" ]; then
	csrf=$(cat integration/csrf-token)
fi

curl 'https://www.messenger.com/messaging/save_thread_nickname/?source=thread_settings&dpr=2' -H 'origin: https://www.messenger.com' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9' -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36' -H 'content-type: application/x-www-form-urlencoded' -H 'accept: */*' -H 'referer: https://www.messenger.com/t/1618325084897514' -H 'authority: www.messenger.com' -H "$cookies" --data 'thread_or_other_fbid=1618325084897514&participant_id='$participant'&nickname='$parameter'&__user=1841839150&__a=1&__req=8n&__be=1&__pc=PHASED%3Amessengerdotcom_pkg&__rev=4560740&fb_dtsg='$csrf --compressed -o /dev/null

